Repository tikv/grpc-rs, pull requests merged in 2018-10, with the labels that each got.

#230 Use stable clippy
  .travis.yml
  benchmark/src/bench.rs
  benchmark/src/client.rs
  benchmark/src/main.rs
  benchmark/src/worker.rs
  compiler/src/codegen.rs
  examples/route_guide/server.rs
  interop/src/bin/client.rs
  interop/src/bin/server.rs
  tests/cases/cancel.rs
  tests/cases/kick.rs
Labels: enhancement

#239 Optionally use openssl instead of boring ssl.
  .travis.yml
  Cargo.toml
  grpc-sys/Cargo.toml
  grpc-sys/build.rs
Labels: enhancement

#221 Create issue templates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/something-else.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/something-else.md
Labels: Documentation

#240 Apply Clang-Tidy's suggestions
  .clang-tidy
  .travis.yml
  grpc-sys/grpc_wrap.cc
  scripts/lint-grpc-sys.sh
  src/server.rs
Labels: Enhancement
