Repository tikv/grpc-rs, pull requests merged in 2019-04, with the labels that each got.

#309 update codegens to move the last instance instead of clone
  compiler/src/codegen.rs
  compiler/src/prost_codegen.rs
Labels: Enhancement, Waiting to Merge

#311 make `./proto` buildable
  proto/Cargo.toml
  proto/build.rs
  proto/build.sh
  proto/example.desc
  proto/proto/grpc/example/helloworld.proto
  proto/proto/grpc/example/route_guide.proto
  proto/testing.desc
Labels: Enhancement, Waiting for Reply

#312 Rust 2018 for grpc-sys
  grpc-sys/Cargo.toml
  grpc-sys/src/lib.rs
Labels: Enhancement, Waiting to Merge

#302 ci: check --all-features
  .travis.yml
Labels: Waiting to Merge

#313 Bump to 0.5.0-alpha.1
  CHANGELOG.md
  Cargo.toml
Labels: Waiting to Merge

#310 Ignore intermittent tests
  interop/tests/tests.rs
  tests/cases/cancel.rs
Labels: Test (Intermittent)

#314 *: fix misspell
  CHANGELOG.md
  src/task/executor.rs
  tests/cases/kick.rs
Labels: Enhancement

#262 support using vendored openssl
  .travis.yml
  Cargo.toml
  grpc-sys/Cargo.toml
  grpc-sys/build.rs
Labels: Enhancement, Waiting to Merge
