Repository tikv/grpc-rs, pull requests merged in 2019-07, with the labels that each got.

#332 grpcio-sys: add bindgen feature
  appveyor.yml
  benchmark/src/bench.rs
  grpc-sys/Cargo.toml
  grpc-sys/build.rs
  grpc-sys/src/grpc_wrap.rs
  grpc-sys/src/lib.rs
  interop/src/client.rs
  interop/src/server.rs
  proto/Cargo.toml
  src/call/mod.rs
  src/call/server.rs
  src/channel.rs
  src/cq.rs
  src/credentials.rs
  src/env.rs
  src/error.rs
  src/log_util.rs
  src/metadata.rs
  src/server.rs
  src/task/executor.rs
  src/task/promise.rs
  tests/cases/cancel.rs
  tests/cases/health_check.rs
Labels: Enhancement, Proposal, gRPC Core

#340 Document OpenSSL compatibility issue and fix
  README.md
Labels: Documentation

#342 Use Git dep for Prost
  Cargo.toml
  compiler/Cargo.toml
  proto/Cargo.toml
  src/metadata.rs
Labels: Build

#357 *: speed up ci
  .travis.yml
  scripts/reset-submodule.cmd
Labels: Build, Enhancement
